### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by stragu** [raatmarien/red-moon#1]
Red Moon 2.1 from F-Droid on Android 4.2.2 crashes straight away, the GUI doesn't even appear.

Using a Fairphone 1.

**Comment by raatmarien** [comment]
Thanks for letting me know! I'll look into it.

**Comment by raatmarien** [comment]
It turns out there was a bug in the android support libraries v23.2.0, which was the latest when I added them. This bug affected pre Lollipop devices and crashed them on the UI load. The new version v23.2.1 fixes this bug, so I've upgraded the dependencies and tested the app on an android 4.2.2 device. The app seems to work now.

**Comment by stragu** [comment]
Great, thank you for looking into it so quickly!

On March 19, 2016 9:58:33 PM AEST, raatmarien <notifications@github.com> wrote:
>It turns out there was a bug in the android support libraries v23.2.0,
>which was the latest when I added them. This bug affected pre Lollipop
>devices and crashed them on the UI load. The new version v23.2.1 fixes
>this bug, so I've upgraded the dependencies and tested the app on an
>android 4.2.2 device. The app seems to work now.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/raatmarien/red-moon/issues/1#issuecomment-198690137

--
Stéphane Guillou
stragu.github.io

Sent from my Fairphone with K-9 Mail. Please excuse my brevity.

You can encrypt our communications by using OpenPGP. My public key
4E211060 is available on the keys.gnupg.net server.
