### ISSUE TITLE
Holdoff for sunset/sunrise operation

### ISSUE THREAD

**Issue by sappjw** [raatmarien/red-moon#100]
I like the ability to have the filter automatically turn on or off with the sunrise or sunset, but I find I'd like it to happen a bit earlier or later. Maybe a setting to hold off past sunset for a certain number of minutes before turning on the filter would be nice.

**Comment by smichel17** [comment]
I agree that slightly more flexibility would be nice. #95 has a huge amount of backend changes and a small amount of fronted changes. They include moving the time toggle settings to a subpage (like secure suspend), which will give us more room to add a setting or two like this without making red moon too.complex, I think.

**Comment by smichel17** [comment]
After thinking about this a bit more, I think:

- I think the actual problem here is really simple: the filter just goes on too early, and we should move it a bit later.
- If we want to offer more flexibility, something like #106 is probably the best way.

**Comment by smichel17** [comment]
#33 discusses fading the filter in, instead of turning on all at once. I'm debating whether fade should always happen, or whether it should be a setting. One option is to offer the fade *duration* as a setting (with 0 for off). In that case, changing the duration would effectively make the filter turn on later, closing this issue.

The point of setting the times from [ your location / the sun ] is automatic configuration. If you have to manually configure a delay, you might as well just set the times yourself. So, if I decide a fade duration setting should not be added, than a simple delay definitely should not be added.

That's a long way of saying, I'm going to close this, and discussion can continue in #33.
