### ISSUE TITLE
Make it optional to disable button backlight

### ISSUE THREAD

**Issue by di72nn** [raatmarien/red-moon#101]
The feature disabling button backlight is fine, but it has as a side-effect: it disables keyboard backlight on devices with a physical QWERTY keyboard, which renders the keyboard almost unusable (it is hard to touch type on a mobile keyboard).

Please make this function optional.

**Comment by smichel17** [comment]
I wonder if there is a way to detect if the device has a backlit keyboard. If so, we could just do this for you instead of making it a setting. If not, this is a reasonable thing to offer.

**Comment by di72nn** [comment]
Someone with a hardware keyboard might want to actually have the feature enabled.

// Anyway, I found that the app can disable this feature (no UI for that, though), I just had to add `<boolean name="pref_key_dim_buttons" value="false" />` to the `com.jmstudios.redmoon_preferences.xml` file.

**Comment by smichel17** [comment]
I think this is worth adding, but I want to think a little bit about where to add it, as I don't want to clog up the main interface with a lot of options. Part of the reason Red Moon is great (IMO) is that it just works.

Options would be adding another category with advanced options (at first, just this), or making a "settings" activity (probably accessed via overflow menu, like most apps) with options to set once and forget, like this and the dark theme.

I'm glad you found a workaround until @raatmarien or myself can add a GUI way to change this.

**Comment by jgkamat** [comment]
+1 on adding a GUI option to turn this off
My hardware buttons are very dim at the highest setting, and tuning them off/dimming them dosen't make sense for me. Thanks for the workaround (but it would be nice to have an easy way to toggle this).

I personally think it would be fine to add another entry under 'other' but an advanced menu option would work too.

**Comment by smichel17** [comment]
Would you see this as an app-wide setting or a per-filter setting?

**Comment by jgkamat** [comment]
I think that it would be fine to have it as an app-wide setting. I don't think very many people will want different settings between different filters.

**Comment by smichel17** [comment]
> // Anyway, I found that the app can disable this feature (no UI for that, though), I just had to add `<boolean name="pref_key_dim_buttons" value="false" />` to the `com.jmstudios.redmoon_preferences.xml` file.

I guess it's "just" if you have root and know a thing or two about how android stores preferences 😛 (psa, check in /data/data/).

**Comment by smichel17** [comment]
I looked into this, and we actually have more flexibility here than I thought we did. We get to choose between using the default behavior and controlling the brightness ourselves, on a (decimal) scale of 0 to 1. So, here's a bunch of options, depending on how "smart" we want to try to be.

- What we're doing right now but with a new preference: Toggle between default behavior and 0 (completely off).
- Instead of turning the button backlight completely off, we could dim it most of the way by passing something like 0.2.
- Use 0 or 0.2, but make the `Lower brightness` setting control both the screen and button backlight.
- Make the Dim value in the filter control both the filter dim level and the button backlight. This gives you a lot more control to set the value.
- Some combination of the previous two approaches, like:
  - If `Lower brightness` is enabled, turn the button backlight all the way off; if it is disabled, set the button backlight based on the dim level.
or
  - If `Lower brightness` is enabled, set the button backlight based on the dim level; if it is disabled, use the default behavior.
- Try to be really smart and figure out #21, so we can use information from the brightness sensor, too.

That's a lot of options. To be honest, I'm not particularly happy with any of them. @jgkamat @di72nn @raatmarien, any opinions?

**Comment by di72nn** [comment]
My only preference is to have the ability to disable that feature without disabling other features.

**Comment by jgkamat** [comment]
I only care about turning it off completely (like @di72nn), because my backlight buttons are dim anyway. 

I personally vote for: If Lower brightness is enabled, set the button backlight based on the dim level; if it is disabled, use the default behavior. (but I don't mind, as long as I can get 100% brightness).

**Comment by smichel17** [comment]
Current behavior is that backlight buttons are always turned completely off. I'd like to leave that as the default since some people want it (#39). So, I think I will add a 3-option setting.

- `Control brightness of hardware buttons`
  - `System managed`
  - `Vary with dim level`
  - `Turn off`

I'm interested in feedback about whether there's room for improvement to make the wording clearer.

**Comment by jgkamat** [comment]
I think that `Vary with dim level` is a little vauge, although I'm not sure what would be better. I can't come up with anything that would be better (without adding a faq or other description). The other two options sound good to me though!

**Comment by smichel17** [comment]
Yeah, I haven't found anything super clear. What about `Same as dim level`? Or just `Same as dim`.

**Comment by raatmarien** [comment]
What about ```Use filter dim level```?

**Comment by smichel17** [comment]
Perfect. It doesn't fit with the mental model I was using to clean up Red Moon's language, but after some thought (hence my delayed reply) I think it's better to change the mental model than this phrasing (see #121).

**Comment by smichel17** [comment]
I don't have any devices that will actually respond to the setting. So, while I think it should work, I'm not 100% sure. @di72nn @jgkamat and @dillbyrne (if you still have a phone that responds to this option), would you mind testing it out?

Aside from the obvious part of checking if the three options work as expected, it would also be great if you can change the setting while the filter is on, and make sure that it updates. One thing I have not implemented (but will if this all works out) is: if the new setting is set to `Use filter dim level`, and you manually change the filter dim level, the backlight level won't change until you turn red moon off and on again.

I put up a debug build here: http://smichel.me/files/red-moon/red-moon-debug-2017-03-07.apk
(let me know if that link stops working and I'll put it up somewhere else)

If you prefer to build yourself, code is in the [button-backlight-setting](https://github.com/raatmarien/red-moon/tree/button-backlight-setting) branch.

**Comment by smichel17** [comment]
One other question: Currently the `Use filter dim level` setting makes the button backlight go between 100% and 10%, same as the dim (you can only go to 90%). Can you try using that option and setting a filter at 90% dim, and let me know whether it feels like it should go all the way off, instead?

**Comment by di72nn** [comment]
Brief testing showed no problems. Settings update correctly while the filter is on.

I have no strong opinion regarding the 90% dim level.
