### ISSUE TITLE
App won't find my location

### ISSUE THREAD

**Issue by elumbella** [raatmarien/red-moon#102]
The app doesn't find the location when in automatic mode. It keeps saying "searching for location" but will not find it. Permissions are definitely given, and other apps can locate just fine.

I'm using Android 6.0.1 on BlackBerry PRIV.

**Comment by smichel17** [comment]
Hard to tell what's going on without a log, and there's not good logging enabled on the fdroid/play store releases.

The only way I can think of in which this might be different from other apps is that Red Moon only uses approximate, network (cell tower) based location, not gps. So if your gps is working but for some reason approximate location is not,  that could be the issue. 

The best way I can think of to test is going to your phone's gps settings and changing Mode to Power saving, then see if other apps still work. Or find another app that uses approximate location.

If you're able to confirm that other apps with only approximate location do not work, then it's probably an issue with your phone. If you can confirm that they work, we can go from there.

**Comment by elumbella** [comment]
I just tried using the power saving mode. I believe my device uses GPS position nonetheless, but only if it is being used (I know because I tried to track a ride with strava while in power saving mode). No idea if approximate position is used for anything, couldn't find anything in the settings.

Other apps therefore work when in power saving mode. But even when I switch from these other apps, that have just been using location, red moon won't pick it up...

Is there a version that has logging enabled?

**Comment by smichel17** [comment]
>Is there a version that has logging enabled?

Unfortunately, not really. You'd need to compile from source. After you downloaded the source, you'll need to change the line `private static final boolean DEBUG = false;` in this file:

https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/preference/LocationPreference.java

to `private static final boolean DEBUG = true;`

**Comment by smichel17** [comment]
I'm in the middle of making a bunch of changes (mostly backend) in #95. I kind of want to say, wait until I'm done with that, to see if it's still an issue. We can also enable logging in that release.

**Comment by matteocoder** [comment]
I can also confirm this bug on Moto G4 with Android 6.0.1 with red moon 2.9.2

Apps like Google maps work fine even with the battery saving setting, but red moon gets stuck.

**Comment by smichel17** [comment]
I believe this is the cause of the bug:

- Android has two ways of finding your location: GPS (precise) and cell/wifi networks (approximate).
  - These have separate permissions that apps can ask for. Red Moon asks for approximate.
- Finding approximate location takes longer than finding precise location.
- Right now, Red Moon only listens for location *while the app is open*.
- Nobody wants to sit around with red moon open for however long it takes to find approximate location.

#95 has two fixes to this:

1. If you've used location services since the last time you rebooted your phone, there is a last known location stored on your phone. Red Moon will now use that instead of waiting to get a new fix on your location. (It will still also try to get a new location, but it'll at least use the last known one while it's waiting).
2. Location updating is now done in a service, so it will continue to listen for an updated location until it finds one, even if you close the app.

I don't think this is a comprehensive fix / enough to close this issue, but it should help mitigate it quite a bit. It will also make it easier to diagnose whether Red Moon is actually unable to get a fix on location, or whether it just takes longer than a reasonable person would be willing to wait.

**Comment by smichel17** [comment]
I put a debug build up at http://smichel.me/files/red-moon/app-debug.apk. @elumbella @matteocoder Could you try it out and see if it works for you?

**Comment by matteocoder** [comment]
Yes the debug build can find the location instantly. Thank you so much for your awesome work!

**Comment by smichel17** [comment]
@elumbella If you can get a location at all, you can close this. I still want to do a little more work on location updating, but that's in #107.

**Comment by elumbella** [comment]
@smichel17 it works perfectly now. Thanks a lot for the effort!
