### ISSUE TITLE
Return phone brightness setting to "Auto" on filter deactivation

### ISSUE THREAD

**Issue by leoauri** [raatmarien/red-moon#131]
Resolution steps (added by @smichel17, unmodified original report below):

- [ ] When we lower or restore the brightness, check if it is still lowered (in addition to whether we have previously lowered it).

---

My phone has an "auto" brightness setting which I always have it on.
At the moment after filter activation - deactivation, the brightness setting seems to be set at some fixed value instead. (Can't test right now though because of #130 )
I'd like it to return to auto in my case, and I guess to be reset to whatever value it had before activation would make the most sense.

**Comment by smichel17** [comment]
The way it should work is based on the `Lower brightness` setting:

- Disabled: Red Moon should never modify your phone's brightness.
- Enabled: When it turns on, Red Moon will turn your phone's "auto" brightness off and set your phone's brightness level to the minimum. When Red Moon turns off, it will set your brightness back how it was beforehand.

You're on Android 4.2.2, correct? To debug, it would help if you check whether this is working at a couple different settings:

- When "auto" is on and when it is off"
  - When the brightness level is high and when it is low (not all the way down, though)

I know that when "auto" is enabled your phone just uses that instead of the brightness level you set, but it still saves the level in the background, and I want to know if Red Moon is saving it too. So, for those you'll need to turn "auto" off, set the level, then turn "auto" back on to test.

If you're able to get a logcat while doing this, that would be twice as awesome.

**Comment by smichel17** [comment]
I did some testing on an Android 4.2 emulator. Things I found:

- The brightness setting seems to be very buggy even without Red Moon installed.
  - For example, I can go to `Settings` -> `Display` -> `Brightness`, and a dialogue appears with a brightness slider and a checkbox for automatic brightness. If I check the checkbox and click OK, then immediately open the dialogue again, the checkbox is unchecked.
  - So, for this I'm not sure I can do anything to fix it.


- Some things are different on older android versions. Red Moon does a check for what version you're running and changes some things, depending. This check appears not to be working.
  - I'll look into this.

**Comment by smichel17** [comment]
The logcat includes this line:

`W/dalvikvm( 9423): VFY: unable to resolve static method 1394: Landroid/provider/Settings$System;.canWrite (Landroid/content/Context;)Z`

In some way this makes sense, since `Settings.System.canWrite(context)` is not available on API 17 (API 17 is Android 4.2, which grants the permission to write settings by default).

Red Moon does a check for what API you're on and never calls that code unless you're on a later API, so I thought the warning meant the code was getting called (ie, the check fails). However, it turns out the check is working so I'm not sure why we are getting this warning at all; maybe it's just Android trying to be helpful and letting us know it exists.

So, I can't find any bug with that.

**Comment by smichel17** [comment]
I think I've found the cause..

**Comment by leoauri** [comment]
Correct, 4.2.2
Any particular filters for the logcat you'd like?

**Comment by leoauri** [comment]
I've not experienced bugginess with the brightness settings so can't corroborate that.

**Comment by leoauri** [comment]
I just tested all of those, toggling the filter with the widget, and the setting was always returned to the preceding value!

**Comment by leoauri** [comment]
Currently can't reproduce.  When I posted it I had just noticed during day to day use and assumed it simply wasn't implemented so.  I'll let you if I notice under what conditions this crops up.

**Comment by smichel17** [comment]
@leoauri Pretty sure I fixed it in ^ that commit. Here's what happened:

Whenever we change to a given state, we tell that state to initialize itself. Things like:

- `OnState` fades in
- `OffState` fades out
- `PreviewState` turns on immediately with no fade
- `OnState` saves the previous brightness,  then lowers the brightness
- `OffState` restores the brightness back to the saved state

When we first started the service, we'd tell the `OffState` to initialize itself, to fix a bug where the main switch wasn't being set correctly. The problem was, that also meant we were trying to restore the brightness, before we'd turned the filter on and saved it, so it just got restored to an arbitrary default value. And then, when you turned Red Moon on, that was the current brightness setting and so *it* got saved for next time, etc. You probably broke the cycle by changing the brightness while Red Moon was open in the background (ie, after we first initialized) but before you turned it on.

**Comment by leoauri** [comment]
Yep, I think it was after phone restart.  Cool!

**Comment by smichel17** [comment]
Going to leave this open because I've been experiencing some (unrelated) issues with brightness on the pre-release v3.0.0.

**Comment by smichel17** [comment]
I think 961255bd fixes the other backlight brightness issues.

**Comment by leoauri** [comment]
I'm still sometimes having issues on 2.10.2, the brightness is sometimes still set at a fixed value rather than auto after the timed deactivation of the filter.  Not always though

**Comment by smichel17** [comment]
@leoauri I don't have time to do a lot of testing to track down the cause. If you (or anyone else reading this) can figure out a way to consistently reproduce this problem, I'll gladly take a swing at it).

**Comment by leoauri** [comment]
Sure, I'll let you know if I can find out how to replicate it.  Thanks

**Comment by smichel17** [comment]
@leoauri I found steps to reproduce:

- Set levels to X
- Select a filter that lowers brightness and start Red Moon
  - Brightness is lowered
- Kill Red Moon
  - Brightness is not restored because android doesn't give us any warning before it kills the process
- Set levels to Y
- Start Red Moon again
- Stop Red Moon
  - Brightness restored to X

Basically now Red Moon tracks whether the brightness has *actually* been lowered, and it won't lower the brightness if it's already lowered or restore it if it's already restored. This makes it safe for me to just call `LowerBrightness()` any time the brightness should be lowered without worrying about whether I already did that: very bug resistant.

But, if you manually change the brightness, Red Moon doesn't know this, so it'll just restore back to what it was. I can add another check when lowering/restoring to see if the brightness has changed since the last time we touched it and act accordingly. I need to think a little big more about exactly what "act accordingly" means. Feedback over at #122 would be appreciated :)
