### ISSUE TITLE
Pause in secure app option not working properly

### ISSUE THREAD

**Issue by jerryn70** [raatmarien/red-moon#151]
After enabling the pause in secure app option iam not able to install or grant permissions. 

Phone : moto x play
Marshmallow 6.0.1
Not rooted

**Comment by smichel17** [comment]
Which version of Red Moon are you using?

App monitoring doesn't actually know if the app is secured against overlays; we just have a list of apps that we know are secured.  The most likely issue is that your phone's package installer / permission request apps have package names we haven't seen before.

I think debugging for the app monitoring is turned off right now. Are you able to get a logcat? If so, I can get you a debug version that will record the package name so we can add it to the list.

I do remember adding a new one to the list not too long ago; which version of Red Moon are you using?

**Comment by cao-** [comment]
@smichel17
Instead of relying on a list of secured apps, I think there's another possibility.  The app "Snap Swipe Drawer", which you can find on the play store, can run as an accessibility service, and thus shows no problems in secured apps.  Isn't it an option to make red moon an accessibility service too?

**Comment by jerryn70** [comment]
Sorry my mistake, there is no issue with this app. 
The reason for not working was iam another blue light filter app
