### ISSUE TITLE
New version 3.0.0 has a bug

### ISSUE THREAD

**Issue by Reedych** [raatmarien/red-moon#156]
I use the fdroid version.

When i toggle on red moon it uses default settings, i want to use only dim, but it also reds my screen even i said him not to do that. To fix this problem i need to change dim level i little and all works, but it's not comfortable to change it always. Now i sit on 2.x version.
Thanks and your program is very good.

**Comment by Reedych** [comment]
to change dim level a* little.

**Comment by Reedych** [comment]
to change dim level a* little.

**Comment by Reedych** [comment]
to change dim level a* little.

**Comment by Reedych** [comment]
to change dim level a* little.

**Comment by smichel17** [comment]
Hi there, thanks for the report :)

I vaguely recall seeing an issue like this. I think it was a side effect of upgrading to v3.0.0. If this bug is the same, it will not happen on a clean install of v3.0.0, and you can permanently fix it by moving a slider and then re-select any profile from the drop-down.

If neither of those work, then it's a different bug, and I'll ask you to test after I finish some work I'm doing now (on profiles) that may fix this bug as a side effect.

**Comment by smichel17** [comment]
I recently noticed that there was a bug in the updating code where Red Moon would not correctly update between versions until the app was opened. From that point, "On unexpected input, the program is undefined."

I have not heard back about this bug or been able to reproduce it, so I'm going to assume it is resolved now. If not, let me know and I'll re-open this issue.
