### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [raatmarien/red-moon#161]
Hi @raatmarien 

I found [this app ](https://play.google.com/store/apps/details?id=com.appwala.brightnesscontroller) on Google Play Store. This guys just took the source code, added some ads and put it on the Google Play Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay), if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GPL3 and this guy is violating it by distributing the app without the source code;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning. (I watch him)

**Comment by smichel17** [comment]
The app looks like it is based on an old version of Red Moon, when we used the MIT license (see #26). Therefore, while it is certainly not ethical, I don't think it is actually in violation of any license.

**Comment by Poussinou** [comment]
He doesn't warn this app is MIT licensed, as the license ask to do.

**Comment by raatmarien** [comment]
Thanks for letting me know!

I downloaded it to see, and it seems to be based on at least v2.9.0, since it includes the suspend in secure apps feature. This means that it is based on our GPLv3 code and it is in clear violation of the license.

This seems to be one of those accounts that just put ads in open source apps, which sucks. I will send an DMCA request to Google, and they should take the app down soon. This will also give a strike on their account, so hopefully they get banned.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by raatmarien** [comment]
I have submitted the DMCA request. I will try to keep you updated.

**Comment by Poussinou** [comment]
Thanks :smiley:

**Comment by smichel17** [comment]
I'm happy to submit one as well in the unlikely event that they need both authors to be on the ticket.

**Comment by Poussinou** [comment]
The app has been removed, thanks for your action. If you find any other one please ping me and give me the link to the fake app!
