### ISSUE TITLE
Root mode

### ISSUE THREAD

**Issue by The0x539** [raatmarien/red-moon#20]
Filters along the lines of what this app currently does may work without root, but on rooted devices, true temperature adjustment along the lines of what's done by cf.lumen or CyanogenMod LiveDisplay is a far better solution, and it would be nice to see such functionality available in a standalone F-Droid app.

**Comment by danialbehzadi** [comment]
Using CyanogenMod LiveDisplay is great!

**Comment by raatmarien** [comment]
Thanks for the feedback!

I'd love to include something like this in Red Moon. However, I've been looking at the source code of CyanogenMod and it seems that LiveDisplay is depends on their modified kernel and the implementation seems to be device specific, so I don't think that would work for Red Moon.

Something like the "CF.Lumen" driver of CF.Lumen seems great, but sadly CF.Lumen is closed source and I don't know how they are able to actually change the colour of what is displayed.

If anyone knows how to do this, any help is welcome!

**Comment by smichel17** [comment]
@mirh

> Also, why not hooking into KCAL

I didn't know about it. Seems like it would be a cool thing to add support for. We'd need to figure out how to translate Red Moon's color/intensity/dim levels into KCAL's Sysfs variables. I haven't touched the math Red Moon uses for generating the filter color; maybe @raatmarien could figure out how that should work.

**Comment by smichel17** [comment]
Also, I think it would be great to get Red Moon more integrated into ~~cyanogenmod~~ LineageOS. Reaching out to those folks is on my list of things I'd like to do, but near the bottom, so don't expect it any time soon :P

**Comment by mirh** [comment]
> If anyone knows how to do this, any help is welcome!

[Hint](https://twitter.com/chainfirexda/status/669826528516161536)

> Also, I think it would be great to get Red Moon more integrated into cyanogenmod LineageOS

Well, as of now there's nothing to talk about in the first place imo. A filter (for as much open source and all) is really no special feat (or feature!) tbh.

**Comment by smichel17** [comment]
> CF.lumen and f.lux

Both of these are closed source, and therefore I am not interested in adding support for them.

> Well, as of now there's nothing to talk about in the first place imo. A filter (for as much open source and all) is really no special feat (or feature!) tbh.

Adding a screen filter is not difficult. The real feature of Red Moon is that it allows a high degree of customization while staying really simple. For contrast, twilight has *less* customization and more complicated settings.

**Comment by The0x539** [comment]
>>CF.lumen and f.lux

>Both of these are closed source and therefore I am not interested in adding support for them.

"Support" for them was never mentioned, just doing something along the lines of what they do, adjusting colors instead of overlaying.

**Comment by smichel17** [comment]
> "Support" for them was never mentioned, just doing something along the lines of what they do, adjusting colors instead of overlaying.

Right, which gets back to

> I don't know how they are able to actually change the colour of what is displayed.

I don't know of any open source app that adjusts colors instead of overlaying. LineageOS (and android itself) both have night modes to reduce blue light from the screen, but they have a lot of source code and it's time consuming to hunt down the place where they adjust the colors. In a cursory web search, I wasn't able to find documentation on it, either.

If I were working on Red Moon full time (or even part time), I'd gladly spend the necessary time to figure out how to adjust colors and implement it. I'd love to have that on my phone! But this is a personal project. I contribute in my time between classes and homework. There are other projects I'd like to spend more time on, too. I simply can't justify spending hours researching this. If you or anyone else can do that part for me, I'll gladly attempt an implementation (this is true of all the issues tagged with `needs information`).

I wish the software ecosystem were different, that funding existed to pay people to work full time on Red Moon and other [FLO](https://wiki.snowdrift.coop/about/free-libre-open) projects. When I'm not spending my free time relaxing or Red Moon, I'm working on Snowdrift.coop, which is trying to create a sustainable funding model for FLO software and other public goods. But unfortunately, that's just not how things are today.

**Comment by mirh** [comment]
> Both of these are closed source, and therefore I am not interested in adding support for them.

I was actually suggesting that I was expecting the behavior of the latter to be quite well documented. 
I know Lightbulb and redshift are 2 very good FOSS desktop applications then. 

>  but they have a lot of source code and it's time consuming to hunt down the place where they adjust the colors

https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/display/NightDisplayService.java
https://github.com/LineageOS/android_hardware_cyanogen/tree/cm-14.1/cmhw/org/cyanogenmod/hardware
https://github.com/LineageOS/android_frameworks_opt_hardware/tree/cm-14.1/src/org/cyanogenmod/hardware
https://github.com/LineageOS/android_hardware_cyanogen/tree/cm-14.1/livedisplay
Also, it's [mentioned](http://www.androidpolice.com/2016/10/21/night-mode-enabler-apps-no-longer-work-android-7-1/) they used to use a GL shader in the past. 

>  Compare to Twilight, which has more complex settings and is less flexible than Red Moon.

Well, TBH I dislike both since the filter is sooo lame, compared to CF.lumen. 😛 
Moreover, I find quite useful the evening/sleep "separated settings".

**Comment by raatmarien** [comment]
Thanks for all the links @mirh, it's very interesting how Lineage does this.

I agree that really filtering the screen would be awesome, but I haven't been able to make that work. I did actually look into how Cyanogen Mod and CF Lumen accomplished it. How Cyanogen mod does it is not really applicable to Red Moon I think, because it is baked into the core operating system. There isn't any API which we can patch into to change the colours AFAIK.

CF Lumen uses root and AFAIK overwrites an core library that android uses to overlay applications. But as CF Lumen isn't FLOSS, I can't really be sure.

>I was actually suggesting that I was expecting the behavior of the latter to be quite well documented.
I know Lightbulb and redshift are 2 very good FOSS desktop applications then.

I don't think how Redshift does it is useful for Android, since Android handles overlaying way differently and is more restricted.

I did spend quite some time trying to get something like this to work a year ago (I even bricked my phone accidentally :P). However, I wasn't able to make it work, and I don't think it is worth the time for me too try it now. I think it is inevitable that a real solution, like how CF Lumen does it, requires root, which I know a large amount of users don't have. Furthermore I think that the overlay approach Red Moon uses right now works quite well, although I know it is not for everyone.

But of course, as is mentioned, if anyone has any concrete ideas on how to implement this, or can even implement it themselves, tips, comments and code are more than welcome!

**Comment by smichel17** [comment]
> **[paraphrased]** I think it is inevitable that a real solution requires root, which most users don't have... AFAIK CF Lumen overwrites an core library that android uses to overlay applications.

These are also the reasons why I'd rather explore getting Red Moon's interface integrated into LineageOS/Android (or creating an API of some sort); I made issue #140 about it.

Red Moon is nearing feature completion. When it gets there, I'll spend some time on stability, then move on to other projects. (I'll still try to support Red Moon on new devices; I just won't be adding anything new.) Overwriting a core library seems like the kind of thing that would be time-consuming to maintain... especially since Google is known for breaking backwards compatibility, even in public apis.

KCAL integration looks like far less ongoing work, so I am willing to add it. Let's make this thread about KCAL, since it's the only root filtering method we're likely to implement. There are two roadblocks that prevent me from implementing KCAL integration:

1. My current device is (unfortunately) not rootable, and my old device is broken. I need to get a development setup with root up and running.

2. We need to figure out some math. The [XDA-Developers thread](https://forum.xda-developers.com/android/software-hacking/dev-kcal-advanced-color-control-t3032080) seems to indicate that KCAL creates some system variables that affect the color temperature of the screen. If you have root, you can write to those variables. These are them:

> /sys/devices/platform/kcal_ctrl.0/kcal - (0-256 0-256 0-256) - Controls R/G/B Multipliers
> /sys/devices/platform/kcal_ctrl.0/kcal_min - (0-256) - Controls minimum RGB Multiplier value
> /sys/devices/platform/kcal_ctrl.0/kcal_enable - (0-1) - Enables/Disables RGB Multiplier Control
> /sys/devices/platform/kcal_ctrl.0/kcal_invert - (0-1) - Enables/Disables Display Inversion Mode
> /sys/devices/platform/kcal_ctrl.0/kcal_sat - (224-383 or 128) - Controls saturation intensity - use 128 for grayscale mode
> /sys/devices/platform/kcal_ctrl.0/kcal_hue - (0-1536) - Controls display hue - may have issues with msm8x26 in the higher values
> /sys/devices/platform/kcal_ctrl.0/kcal_val - (128-383) - Controls display value
> /sys/devices/platform/kcal_ctrl.0/kcal_cont - (128-383) - Controls display contrast


So the question is, **which of those do we set to what values, in order to make the current controls work well in root mode?**  I'm not very familiar with the color calculations we do. @raatmarien, do you have any insight?

**Comment by mirh** [comment]
> These are also the reasons why I'd rather explore getting Red Moon's interface integrated into LineageOS/Android (or creating an API of some sort); I made issue #140 about it.

Tbh I don't see this app (or any one) really as improving all that much situation in those cases. 
On the other hand, what's actually incredibly lacking is a FOSS alternative for phones with stock (or older custom) roms. 

> Overwriting a core library seems like the kind of thing that would be time-consuming to maintain... especially since Google is known for breaking backwards compatibility, even in public apis.

Not like one couldn't already call it a day even if support stopped on nougat, given where most of devices are. 

> My current device is (unfortunately) not rootable

Devices with no way to flash a custom kernel, or with nobody willing to develop one.. Sure, okay. 
But I find very hard to believe this.

**Comment by smichel17** [comment]
> Tbh I don't see this app (or any one) really as improving all that much situation in those cases.

Certainly not as much, but I think it would still help some. For example, I know someone who uses Red Moon on top of livedisplay because livedisplay doesn't do enough for him on its own.

> On the other hand, what's actually incredibly lacking is a FOSS alternative for phones with stock (or older custom) roms.


> Not like one couldn't already call it a day even if support stopped on nougat, given where most of devices are.

That's fair. Integration for new devices, driver solution for old ones.

> Devices with no way to flash a custom kernel, or with nobody willing to develop one.. Sure, okay. But I find very hard to believe this.

I haven't checked XDA for a few months, so maybe something has changed. I doubt it, though; the AT&T galaxy S6 forces "security updates" with no way to disable them. I got it as a replacement device and didn't really have a choice in the model :(

https://forum.xda-developers.com/att-galaxy-s6

**Comment by mirh** [comment]
I see. 
And tbh the problems seem two: both a difficult device to tinker with, and also a community that even that of potato phones with forums cluttered by indian illiterates looks better. 
According to [this post](https://forum.xda-developers.com/att-galaxy-s6/general/root-t3566743/page4) anyway, it's highly recommended you avoid getting anything higher than february patch level. 
With enough luck in some time dirtycow should land.

**Comment by smichel17** [comment]
Closing in favor of #150

**Comment by mirh** [comment]
This was in the news today
https://github.com/corphish/NightLight

**Comment by NoahAndrews** [comment]
Seems pretty cool for custom kernel users

**Comment by smichel17** [comment]
We are also pretty close to root mode in Red Moon. We basically just need to wrestle with the android ndk to get it working, at this point. The semester is in full swing at the moment so I don't know when I'll have a chance to do that next, but it should only be a week or so of testing and polishing up the edges, whenever I *do* find the time.
