### ISSUE TITLE
Automatic adjustment based on environment

### ISSUE THREAD

**Issue by jluttine** [raatmarien/red-moon#21]
This is a great app, thanks a ton! I've been dreaming about this kind of app for a long time. :+1: 

I'd like to make a feature proposal: the screen filter would adjust automatically based on the brightness of the environment. I have automatic brightness adjustment in Cyanogenmod but it is not sufficient, I'd like to have this screen filtering to adjust automatically too, in a similar way.

However, I'm not sure how to make it easily configurable. Perhaps it would only be the intensity level that needs to change as a function of environment brightness. The user could have one or few parameters to tune that or, as in my screen brightness config, the user could create "setpoints", that is, define light sensor values in lux and the corresponding intensity levels.

**Comment by jluttine** [comment]
Just to make this simpler: activate the filter automatically at a certain customizable light censor value.

**Comment by raatmarien** [comment]
Thanks for the feedback, this seems like a very useful feature.

I will look into adding a feature like this in the future, however I don't know how easy it will be to implement. If anyone wants to try and implement something like this, pull requests are welcome!

**Comment by smichel17** [comment]
I'd like to limit the scope of this issue even more, down to just the backend functionality for this (ie, the ability to be notified when the light sensor value changes). The rest is covered by #122.

**Comment by smichel17** [comment]
Thinking about this a little. The system already has an "automatic brightness" feature, that is often optimized for the hardware... in short, I don't think we should try to detect the ambient light level.

I do think it would make sense to allow more granularity in the hardware backlight controls (right now it's either full dim or manual control). I'm going to close this in favor of #122.

**Comment by decadent** [comment]
I have to disagree that this can be trusted to the system's automatic brightness control. I don't know about the situation in stock Android or custom ROMs, but phone vendors' brightness algorithms are rather deficient in all phones that I've used. There are already several apps to correct this, e.g. Lux and CF.lumen, and a slew of 'dark filters' to lower the brightness below the minimum. Bundling both brightness and red filter control in one app makes all the sense.

Moreover, ambient brightness measurements can help the functionality of the red filter. E.g. if I step into a mall at night, strong red filter isn't of much use to me under the fluorescent lights: I have to disable it to see the screen.

However, I don't know about the power usage and optimization factors here. Since the system already measures the brightness anyway, I would hope that there's an event-subscription API instead of polling, or that measurements of the app instead of those of the system wouldn't make much difference. And the feature could be optional, to satisfy the power-conscious users.

**Comment by mirh** [comment]
> I have to disagree that this can be trusted to the system's automatic brightness control.

I used to have to adjust it like 4-5 times a day once, but I swear whatever machine learning magic they pulled off with Pie (at least in the rom of my XZ2...) is fucking gold. 

> E.g. if I step into a mall at night, strong red filter isn't of much use to me under the fluorescent lights

I mean.. I'm not sure if ALS can detect light temperature. If any time and position is what could surely call it a day (and at least Sony has a nice super straightforward utility to link night mode to that)

> However, I don't know about the power usage and optimization factors here.

I don't really think battery considerations have ever been a concern with regards to any one of these cases tbh...

**Comment by smichel17** [comment]
> I don't really think battery considerations have ever been a concern with regards to any one of these cases tbh...

Battery is not much of a concern for Red Moon in general because we stop doing anything when the screen turns off and when the screen is on its power draw dwarfs pretty much everything else, unless you're mining cryptocurrency on your phone or something.

**Comment by mirh** [comment]
I *think* he was indeed referring to the power draw of the screen.

**Comment by smichel17** [comment]
I was clarifying, not disagreeing :)

The main concern with long-running services is minimizing how often you wake the phone up. We do that at most twice per day (on/off).
