### ISSUE TITLE
Red Moon on Google Play store?

### ISSUE THREAD

**Issue by bungabunga** [raatmarien/red-moon#30]
Is there any chance to release Red Moon on Google Play store?

I am cautious to use apps from F-droid that are signed with a single F-droid key, not the keys of their developers.

If you don't wish to release on Play store the alternative would be to make a Red Moon F-droid repository or simply release the developer-signed app on Github.

Thanks for your consideration.

**Comment by raatmarien** [comment]
Thanks for your feedback.

I do plan on eventually adding Red Moon to the Google Play Store, but that may be a while off.

It may be an option for you to build Red Moon yourself, since that gives you the most assurance that it hasn't been tampered with. However, I will also try to add a self-signed APK to the next release.

**Comment by raatmarien** [comment]
I've attached a self-signed APK to [the new release](https://github.com/raatmarien/red-moon/releases/tag/v2.7.0).

**Comment by raatmarien** [comment]
I released Red Moon on the Google Play store today!

https://play.google.com/store/apps/details?id=com.jmstudios.redmoon
