### ISSUE TITLE
Automatic turn on/off based on sun not.working

### ISSUE THREAD

**Issue by tspacepilot** [raatmarien/red-moon#44]
I touch automatic turn on/off and select "based on sun" and yet I have not seen the filter come on or off automatically.   What am I missing?

**Comment by smichel17** [comment]
Did you update the location?

**Comment by smichel17** [comment]
@raatmarien When the user switches from `manual` or `custom` to `sun`, Red Moon should probably try to update location immediately (in addition to being able to manually update by tapping the 'location' setting, and attempting to update in the background each time the filter toggles).

**Comment by tspacepilot** [comment]
@smichel17 I do not see this setting.  Below "Automatic filter" I see "startup",  "appearance" and "contact".  I'm using 2.6.2 from f-droid.

**Comment by smichel17** [comment]
@tspacepilot Try upgrading to 2.7.X. There have been a lot of UX improvements.

**Comment by tspacepilot** [comment]
@smichel17 thanks!  Upgraded and I see the location button now.  @raatmarien it would be really great to add the ability to set a location "by hand" (a postal code, or perhaps just degrees of latitude --- I suppose the latter is all you actually need to compute sunset times) rather than relying on the location services of the device.

**Comment by smichel17** [comment]
See #5

**Comment by raatmarien** [comment]
@smichel17, Red Moon v2.7.0+ already does silently update the location whenever the user switches to "Automatic (sun)" mode. However since android only gives the location once every 45 second, users usually manually search for a location before one is found. 

@tspacepilot, thanks for the feedback. I'm indeed looking into letting users manually enter their location.
