### ISSUE TITLE
Make the notification like in 2.6.3 again

### ISSUE THREAD

**Issue by theScrabi** [raatmarien/red-moon#45]
Hello,

the notification in 2.6.2 was pretty usefull, since you could make it stop to apere during the day. The new notification is ab it annoying, since you have to kill the whole app in order to make it go away

Rgds schabi

**Comment by smichel17** [comment]
This is planned. See #36.

**Comment by smichel17** [comment]
@theScrabi In the meantime, if you want to never see the notification, you can long press on the red moon icon and then drag it to the top, "App info" -- on that screen, there's a check box "Show notifications". If you uncheck that, notifications will never appear (downside: you'll have to open the app to pause, because there is no notification).

**Comment by theScrabi** [comment]
All right thanks.
