### ISSUE TITLE
Improve notification

### ISSUE THREAD

**Issue by M2ck** [raatmarien/red-moon#58]
- [x] Add Resume/Pause labels near Resume/Pause buttons (especially because on Android N only labels are shown, see [here](http://developer.android.com/preview/features/notification-updates.html#direct))
- [x] Rewrite "Paused" and "Running. Pause to install apks" strings for avoid something of redundant and obvious with the corresponding label below

**Comment by Salamandar** [comment]
- [ ] Add +/- buttons for luminosity like in Darker ?

**Comment by raatmarien** [comment]
>- [ ] Add +/- buttons for luminosity like in Darker ? 

Although I see the use of this feature for Darker, I don't think it is appropriate for Red Moon, since the Red Moon filter can't be changed with only one value. Whereas Darker has just the one setting for the strength of the filter, Red Moon has both the intensity and the dim level. Because of this I think it is more convenient for the user to just make a few profiles that they regularly use and switch between them using the button in the notification.

**Comment by smichel17** [comment]
For part 2, what if we removed the 'Running' and 'Paused' parts of those strings (ie, removed the 'Paused' string entirely and only show 'Pause to install apks' when the auto-pause feature is disabled. Between the pause/resume button and the color of the screen, it's pretty painfully obvious whether Red Moon is running or not.

**Comment by smichel17** [comment]
I put the name of the active profile in the notification text instead of the obvious/redundant "Paused" or "Running. Pause to install apks", and renamed the action for switching profiles to "Next profile".

To pre-emptively address the concern that users may not know to pause the apk, see #114.
