### ISSUE TITLE
System is very slow when red moon is activated

### ISSUE THREAD

**Issue by robinpaulson** [raatmarien/red-moon#89]
Hi, i'm using Red Moon on Replicant (a free software derivative of Android) 4.2.2, on a Samsung Galaxy S3. When Red Moon activates it self at sun down, my device straight away becomes much slower to react; screen drags, button clicks, everything now has a delay. I am using the most recent version, installed from f-droid.

Has anyone else had similar problems?
Any suggestions for debug info I might provide to track down the issue?

Cheers,

Robin

**Comment by raatmarien** [comment]
Thanks for letting me know!

I've tried Red Moon a few times on a galaxy nexus with Replicant, and the same problem occurs there. I've tried to fix this, by optimizing the code used for drawing, but this didn't work. It seems the problem is with Replicant not having a GPU driver, which makes the filter draw on the CPU, slowing it down. So it seems that it isn't possible to use Red Moon without slow downs on Replicant. If you are looking for a free software replacement, I suggest looking at 'Dimmer' or manipulating your phone's screen calibration directly from the settings to filter blue light out. Sorry for the inconvenience

**Comment by raatmarien** [comment]
Hey Robin,

Thanks for letting me know!

I've tried Red Moon a few times on a galaxy nexus with Replicant, and the same problem occurs there. I've tried to fix this, by optimizing the code used for drawing, but this didn't work. It seems the problem is with Replicant not having a GPU driver, which makes the filter draw on the CPU, slowing it down. So it seems that it isn't possible to use Red Moon without slow downs on Replicant. If you are looking for a free software replacement, I suggest looking at 'Dimmer' or manipulating your phone's screen calibration directly from the settings to filter blue light out. Sorry for the inconvenience!
